all:
	gcc matmat_original.c -o pmatmat_original -fopenmp
	gcc matmat_v1.c -o pmatmat_v1 -fopenmp
	gcc matmat_v2.c -o pmatmat_v2 -fopenmp
	gcc matmat_v3.c -o pmatmat_v3 -fopenmp
	gcc matmat_v4.c -o pmatmat_v4 -fopenmp
	
clean:
	rm pmatmat*
